const Cards = [
    {
      imgSrc: "/images/listings/g1-15.jpg",
      tag: "FEATURED",
      price: "₹14,000 / mo",
      title: "Equestrian Family Home",
      location: "California City, CA, USA",
      bed: "3 bed",
      bath: "4 bath",
      sqft: "1200 sqft",
    },
    {
      imgSrc: "/images/listings/g1-16.jpg",
      tag: "",
      price: "₹82,000 / mo",
      title: "Luxury villa in Rego Park",
      location: "California City, CA, USA",
      bed: "3 bed",
      bath: "4 bath",
      sqft: "1200 sqft",
    },
    {
      imgSrc: "/images/listings/g1-17.jpg",
      tag: "",
      price: "₹63,000 / mo",
      title: "Villa on Hollywood Boulevard",
      location: "California City, CA, USA",
      bed: "3 bed",
      bath: "4 bath",
      sqft: "1200 sqft",
    },
    {
      imgSrc: "/images/listings/g1-10.jpg",
      tag: "FEATURED",
      price: "₹63,000 / mo",
      title: "Villa on Hollywood Boulevard",
      location: "California City, CA, USA",
      bed: "3 bed",
      bath: "4 bath",
      sqft: "1200 sqft",
    },
    {
      imgSrc: "/images/listings/g1-11.jpg",
      tag: "FEATURED",
      price: "₹14,000 / mo",
      title: "Triple Story House for Rent",
      location: "California City, CA, USA",
      bed: "3 bed",
      bath: "4 bath",
      sqft: "1200 sqft",
    },
    {
      imgSrc: "/images/listings/g1-12.jpg",
      tag: "",
      price: "₹82,000 / mo",
      title: "Northwest Office Space",
      location: "California City, CA, USA",
      bed: "3 bed",
      bath: "4 bath",
      sqft: "1200 sqft",
    },
    {
      imgSrc: "/images/listings/g1-13.jpg",
      tag: "",
      price: "₹63,000 / mo",
      title: "Affordable Green Villa House",
      location: "California City, CA, USA",
      bed: "3 bed",
      bath: "4 bath",
      sqft: "1200 sqft",
    },
    {
      imgSrc: "/images/listings/g1-14.jpg",
      tag: "FEATURED",
      price: "₹63,000 / mo",
      title: "Sky Pool Villa House",
      location: "California City, CA, USA",
      bed: "3 bed",
      bath: "4 bath",
      sqft: "1200 sqft",
    },
    // Add more listings as needed
  ];
  

  export default Cards;